name: 'Codeowner Validator'
description: 'Will validate that every file in the repo has a valid codeowner'
author: 'Robert.maxwell@udemy.com'

# Define your inputs here.
inputs:
  github-token:
    description: 'Github token'
    required: true
  codeowners-file:
    description: 'Path to the codeowners file'
    required: false
    default: '.github/CODEOWNERS'

runs:
  using: node20
  main: dist/index.js
